### ISSUE TITLE
package-list error

### ISSUE THREAD

**Issue by ccpwcn** [subchen/javadoc.chm#2]
Run project for JDK 1.8 failed.
Detail:
addAnchor(0) : E:\Users\Administrator.WIN-01509032133\Downloads\jdk-8u66-docs-all\docs\api\javax\print\attribute\standard\PrinterLocation.html
addAnchor(0) : E:\Users\Administrator.WIN-01509032133\Downloads\jdk-8u66-docs-all\docs\jre\api\plugin\dom\org\w3c\dom\html\class-use\HTMLQuoteElement.html
Exception in thread "main" java.io.FileNotFoundException: File 'E:\Users\Administrator.WIN-01509032133\Downloads\jdk-8u66-docs-all\docs\package-list' does not exist
    at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
    at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)
    at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1806)
    at jetbrick.tools.chm.reader.JavaInfoReader.getAllPackages(JavaInfoReader.java:39)
    at jetbrick.tools.chm.reader.JavaInfoReader.getJavaInfo(JavaInfoReader.java:35)
    at jetbrick.tools.chm.reader.ApiReader.getApiContext(ApiReader.java:57)
    at jetbrick.tools.chm.Application.main(Application.java:50)

**Comment by subchen** [comment]
Could you provide your API docs name or url? Which Jdk version is used for building?

**Comment by ccpwcn** [comment]
when failed, try and try again...
then, The path "E:\Users\Administrator.WIN-01509032133\Downloads\jdk-8u66-docs-all" is error, when i build the project, this path has be specified on command-line parameter, the right path is "E:\Users\Administrator.WIN-01509032133\Downloads\jdk-8u66-docs-all\docs", the sub-directory named "docs" has be lost. What I mean to say was the sub-directory named "docs" must be include, rebuild it, successfully.
