### ISSUE TITLE
java -Xms256m -Xmx512m -jar javadoc.chm-2.1.0.jar <javadoc-api-dir> <file-encoding>

### ISSUE THREAD

**Issue by fjalimama** [subchen/javadoc.chm#3]
报错了   syntax error near unexpected token `<'

改成java -Xms256m -Xmx512m -jar javadoc.chm-2.1.0.jar 还是报错 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at jerbrick.tools.chm.reader.ApiReader.getAllFiles(ApiReader.java:105)
        at jerbrick.tools.chm.reader.ApiReader.getApiContext(ApiReader.java:38)
        at jerbrick.tools.chm.Application.main(Application.java:50)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more

**Comment by subchen** [comment]
1. 首先你需要从 oracle 官网下载 javadoc zip 包，然后解压
https://www.oracle.com/technetwork/java/javase/documentation/index.html

2. git clone 整个项目

```
curl -fSL https://github.com/subchen/javadoc.chm/archive/2.1.0.tar.gz -o javadoc.chm-2.1.0.tar.gz
tar -zxvf javadoc.chm-2.1.0.tar.gz
```

3. ./run.bat <javadoc zip 解压目录> <编码>
如果下载中文版的，编码应该是 GBK，英文版的应该是 utf-8 或者 iso8859-1

**Comment by IceCokes** [comment]
Windows环境下最简单的方法:将lib的jar包放到JRE的扩展类文件夹中(%JAVA_HOME%/jre/lib/ext)

**Comment by hellkity** [comment]
您好，我已经收到您的邮件。由于现在不方便上网，我稍后将会尽快给您回复。
